[package]
name = "hal"
version = "0.2.0"
edition = "2021"

[dependencies]
riscv = { version = "0.7.0", optional = true }
riscv-rt = { version = "0.8.0", optional = true }
embedded-hal = "0.2.6"

[features]
riscv = ["riscv", "riscv-rt"]
atmega = []

[build]
target = "riscv32-unknown-none-elf"
