[build]
target = "xtensa-esp32-none-elf"  # ou "avr-unknown-gnu-atmega328" selon votre besoin

[target.xtensa-esp32-none-elf]
runner = "espflash --monitor"

[target.avr-unknown-gnu-atmega328]
runner = "avrdude -p atmega328p -c arduino -U flash:w:target/avr/debug/your_program.hex:i"